### ISSUE TITLE
Major security issues? 🤔

### ISSUE THREAD

**Issue by reimertz** [phiresky/encrypted-gist#1]
Nice work, I just see one major issue with this tool.

Once the initial gist is uploaded, since you set 'public:true', 
it's indexable by any crawler, and searchable by any user at https://gist.github.com/search.

So ironically, it seems gists "encrypted" with this tool is only encrypted for the user wanting to protect their file in the first place? 🤔

Please correct me if I am wrong.

**Comment by phiresky** [comment]
True, the published gist is public. But it doesn't matter that the gist is public, because the data is encrypted; and thus indistinguishable from completely random data without the decryption key, which is stored in the #-part of the URL which is never sent anywhere . For example, looking at this gist https://gist.github.com/anonymous/d6c12f31f25511e75561 it's mathematically impossible to tell that it encodes an image (assuming my code and AES is not broken and you don't have hundreds of decades of time).

You need the decryption key (MxxLThUm9bwx5ECH6z0UlQ) to decode it into this image: https://phiresky.github.io/encrypted-gist/#1sEvMfJVEedVYQ!MxxLThUm9bwx5ECH6z0UlQ

The only thing you can tell from the enrypted data is how large the file is, because that's impossible to completely hide.

Not sure why I set the gist to public, because it seems like it would work just as well without it being public, but I can't think of a reason for it to be private either.

Let me know if I misunderstood your concern.

**Comment by reimertz** [comment]
@phiresky, i am very sorry.

__just__ looked through your code more carefully and realized that you first upload content encrypted, not un-encrypted. So went here to edit my commen, apologize and close the issue. 

You are completely correct, there shouldn't be any issues with your implementation. Sorry for the confusion and thanks for writing this tool. 

It's a very helpful for me since i'm trying to create an open-sourced, anonymous and encrypted blogging platform and your code is the final piece of the puzzle. 👏
